apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-api
spec:
  replicas: 2  # Quantidade de réplicas da aplicação
  selector:
    matchLabels:
      app: video-processor-api  # Seleciona pods com essa label
  template:
    metadata:
      labels:
        app: video-processor-api  # Associa esse label ao pod criado
    spec:
      containers:
      - name: video-processor-api
        image: edsontecno/video-processor-api:latest  # Imagem do Node.js 
        ports:
        - containerPort: 3000  # Porta exposta pela aplicação
        resources:
          requests:   # Recursos mínimos para cada pod
            memory: "512Mi"
            cpu: "100m"
          limits:     # Limites máximos para cada pod
            memory: "1024Mi"
            cpu: "1"        
        env:
        - name: SERVER_PORT
          value: "3000"  # Porta do servidor
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: AWS_REGION
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: AWS_SECRET_ACCESS_KEY      
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: AWS_SESSION_TOKEN          
        - name: AWS_S3_BUCKET_NAME
          value: repo-videos-fiap
        - name: QUEUE_PROCESSAR
          value: processar.fifo
        - name: QUEUE_PROCESSADOS
          value: processados.fifo 
        - name: AWS_SQS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: AWS_SQS_ENDPOINT
        - name: NODE_ENV
          value: production
